version: '3.4'

services:
  trainer:
    image: ${DOCKER_REGISTRY-}trainer
    build:
      context: .
      dockerfile: Trainer/Dockerfile
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports: 
     - 1434:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Like1_Like2"
      