//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Trainer.Application.Templates {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class EmailTemplates {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Trainer.Application.Templates.EmailTemplates", typeof(EmailTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;
        ///    &lt;meta name=&quot;x-apple-disable-message-reformatting&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;!--[if mso]&gt;
        ///    &lt;noscript&gt;
        ///      &lt;xml&gt;
        ///        &lt;o:OfficeDocumentSettings&gt;
        ///          &lt;o:PixelsPerInch&gt;96&lt;/o:PixelsPerInch&gt;
        ///        &lt;/o:OfficeDocumentSettings&gt;
        ///      &lt;/xml&gt;
        ///    &lt;/noscript&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ApproveUser {
            get {
                return ResourceManager.GetString("ApproveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;
        ///    &lt;meta name=&quot;x-apple-disable-message-reformatting&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;!--[if mso]&gt;
        ///    &lt;noscript&gt;
        ///      &lt;xml&gt;
        ///        &lt;o:OfficeDocumentSettings&gt;
        ///          &lt;o:PixelsPerInch&gt;96&lt;/o:PixelsPerInch&gt;
        ///        &lt;/o:OfficeDocumentSettings&gt;
        ///      &lt;/xml&gt;
        ///    &lt;/noscript&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlockUser {
            get {
                return ResourceManager.GetString("BlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;
        ///    &lt;meta name=&quot;x-apple-disable-message-reformatting&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;!--[if mso]&gt;
        ///    &lt;noscript&gt;
        ///      &lt;xml&gt;
        ///        &lt;o:OfficeDocumentSettings&gt;
        ///          &lt;o:PixelsPerInch&gt;96&lt;/o:PixelsPerInch&gt;
        ///        &lt;/o:OfficeDocumentSettings&gt;
        ///      &lt;/xml&gt;
        ///    &lt;/noscript&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CodeEmail {
            get {
                return ResourceManager.GetString("CodeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;
        ///    &lt;meta name=&quot;x-apple-disable-message-reformatting&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;!--[if mso]&gt;
        ///    &lt;noscript&gt;
        ///      &lt;xml&gt;
        ///        &lt;o:OfficeDocumentSettings&gt;
        ///          &lt;o:PixelsPerInch&gt;96&lt;/o:PixelsPerInch&gt;
        ///        &lt;/o:OfficeDocumentSettings&gt;
        ///      &lt;/xml&gt;
        ///    &lt;/noscript&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeclineUser {
            get {
                return ResourceManager.GetString("DeclineUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;
        ///    &lt;meta name=&quot;x-apple-disable-message-reformatting&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;!--[if mso]&gt;
        ///    &lt;noscript&gt;
        ///      &lt;xml&gt;
        ///        &lt;o:OfficeDocumentSettings&gt;
        ///          &lt;o:PixelsPerInch&gt;96&lt;/o:PixelsPerInch&gt;
        ///        &lt;/o:OfficeDocumentSettings&gt;
        ///      &lt;/xml&gt;
        ///    &lt;/noscript&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;
        ///    &lt;meta name=&quot;x-apple-disable-message-reformatting&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;!--[if mso]&gt;
        ///    &lt;noscript&gt;
        ///      &lt;xml&gt;
        ///        &lt;o:OfficeDocumentSettings&gt;
        ///          &lt;o:PixelsPerInch&gt;96&lt;/o:PixelsPerInch&gt;
        ///        &lt;/o:OfficeDocumentSettings&gt;
        ///      &lt;/xml&gt;
        ///    &lt;/noscript&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ExaminationEmail {
            get {
                return ResourceManager.GetString("ExaminationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt;
        ///    &lt;meta name=&quot;x-apple-disable-message-reformatting&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;!--[if mso]&gt;
        ///    &lt;noscript&gt;
        ///      &lt;xml&gt;
        ///        &lt;o:OfficeDocumentSettings&gt;
        ///          &lt;o:PixelsPerInch&gt;96&lt;/o:PixelsPerInch&gt;
        ///        &lt;/o:OfficeDocumentSettings&gt;
        ///      &lt;/xml&gt;
        ///    &lt;/noscript&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UnBlockUser {
            get {
                return ResourceManager.GetString("UnBlockUser", resourceCulture);
            }
        }
    }
}
