export class UsersError {
  approveUserEnable:boolean;
  approveUserEmailEnable:boolean;
  blockUserEnable:boolean;
  blockUserEmailEnable:boolean;
  changeRoleEnable:boolean;
  declineUserEnable:boolean;
  declineUserEmailEnable:boolean;
  deleteUserEnable:boolean;
  deleteUserEmailEnable:boolean;
  unBlockUserEnable:boolean;
  unBlockUserEmailEnable:boolean;
  resetPasswordUserEnable:boolean;
  getBaseUserEnable:boolean;
  getRandomBaseUserEnable:boolean;
  getBaseUsersEnable:boolean;
  getRandomBaseUsersEnable:boolean;
  signInEnable:boolean;
}
