# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: Trainer.Backend/Trainer
      run: dotnet restore Trainer.sln
      
    - name: Build
      working-directory: Trainer.Backend/Trainer
      run: dotnet build Trainer.sln --no-restore
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      working-directory: Trainer.Frontend/Trainer
      run: npm install

    - name: Build
      working-directory: Trainer.Frontend/Trainer
      run: npm run build
